language: ruby

rvm:
- "2.5.3"

gemfile:
  - Gemfile

script:
  - bundle exec rake db:schema:load
  - bundle exec rake test:prepare
  - bundle exec rake test

notifications:
  email:
    on_success: never
    on_failure: never
