scope: 'read_products, read_orders'

order_webhook:
  topic: "orders/create"
  address: "http://taxreceipts.herokuapp.com/order.json"
  #address:  "https://6fecf05.ngrok.com/order.json"
  format: "json"

uninstall_webhook:
  topic: "app/uninstalled"
  address: "http://taxreceipts.herokuapp.com/uninstall.json"
  #address:  "https://6fecf05.ngrok.com/uninstall.json"
  format: "json"
